# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MySecretary (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MySecretary (iOS)
	pod 'Firebase/Analytics'

end

target 'MySecretary (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MySecretary (macOS)
	pod 'Firebase/Analytics'

end
